tabs:
  regional: "RegionalData"
  national: "NationalData"
  subnational: "SubnationalData"
  refugees_series: "RefugeesSeries"
  idps_macro: "IDPsMacro"
  fatalities: "Fatalities"
  timeseries_casualties: "Casualties"
  sources: "Sources"


googlesheets:
  prod: "https://docs.google.com/spreadsheets/d/1a8OfzVRU5ZKDR9EoPu0TGSqb-HqedbmJC9v9jyYGDDE/edit#gid=0"
  test: "https://docs.google.com/spreadsheets/d/1wqnTR1i-DcFwh68BGGQgi4U9N4onLxqXvsmIhkchJVk/edit#gid=0"
  scratch: "https://docs.google.com/spreadsheets/d/1XfsqmwE9F0X551WfQU6KPqvlE0mW1auInxMSW_fj6Rc/edit#gid=0"

json:
  filepath: "all.json"

additional_sources:
  - indicator: "#date+start+conflict"
    source_date: "2022-02-24"
    source: "Meduza"
    source_url: "https://meduza.io/en/news/2022/02/24/putin-announces-start-of-military-operation-in-eastern-ukraine"

# national
scraper_national:
  population:
    source: "WorldPop/UNFPA"
    dataset: "gridded-population-estimates-for-ukraine-using-un-cod-ps-estimates-2020-version-1-0"
    url: "http://api.worldbank.org/v2/en/indicator/SP.POP.TOTL?downloadformat=excel&dataformat=list"
    format: "xls"
    sheet: "Data"
    headers: 3
    prefilter: "Value != ''"
    admin:
      - "Country Code"
    date: "Year"
    date_type: "year"
    input:
      - "Value"
    output:
      - "Population"
    output_hxl:
      - "#population"
  casualties:
    source: "OHCHR"
    source_url: "https://data.humdata.org/dataset/ukraine-key-figures-2022"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQIdedbZz0ehRC0b4fsWiP14R7MdtU1mpmwAkuXUPElSah2AWCURKGALFDuHjvyJUL8vzZAt3R1B5qg/pub?gid=0&single=true&output=csv"
    format: "csv"
    headers: 2
    admin_single: "UKR"
    date: "Date"
    date_type: "date"
    input:
      - "Civilian casualities(OHCHR) - Killed"
      - "Civilian casualities(OHCHR) - Injured"
    output:
      - "CiviliansKilled"
      - "CiviliansInjured"
    output_hxl:
      - "#affected+killed"
      - "#affected+injured"
  attacks_education:
    source: "Multiple Sources"
    source_url: "https://data.humdata.org/dataset/ukraine-key-figures-2022"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQIdedbZz0ehRC0b4fsWiP14R7MdtU1mpmwAkuXUPElSah2AWCURKGALFDuHjvyJUL8vzZAt3R1B5qg/pub?gid=0&single=true&output=csv"
    format: "csv"
    headers: 2
    admin_single: "UKR"
    prefilter: "Attacks on Education Facilities != ''"
    date: "Date"
    date_type: "date"
    use_date: True
    input:
      - "Attacks on Education Facilities"
    output:
      - "AttacksOnEducation"
    output_hxl:
      - "#indicator+attacks+education+num"
  attacks_healthcare:
    source: "WHO"
    source_url: "https://data.humdata.org/dataset/ukraine-who-ssa"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQIdedbZz0ehRC0b4fsWiP14R7MdtU1mpmwAkuXUPElSah2AWCURKGALFDuHjvyJUL8vzZAt3R1B5qg/pub?gid=0&single=true&output=csv"
    format: "csv"
    headers: 2
    admin_single: "UKR"
    prefilter: "Attacks on Health Care != ''"
    date: "Date"
    date_type: "date"
    use_date: True
    input:
      - "Attacks on Health Care"
    output:
      - "AttacksOnHealthcare"
    output_hxl:
      - "#indicator+attacks+healthcare+num"
  numberoforgs:
    dataset: "ukraine-who-does-what-where-3w"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQIdedbZz0ehRC0b4fsWiP14R7MdtU1mpmwAkuXUPElSah2AWCURKGALFDuHjvyJUL8vzZAt3R1B5qg/pub?gid=0&single=true&output=csv"
    format: "csv"
    headers: 2
    admin_single: "UKR"
    prefilter: "Number of Organisations != ''"
    date: "Date"
    date_type: "date"
    use_date: True
    input:
      - "Number of Organisations"
    output:
      - "OrgCount"
    output_hxl:
      - "#org+count+num"
  numberreached:
    dataset: "ukraine-who-does-what-where-3w"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQIdedbZz0ehRC0b4fsWiP14R7MdtU1mpmwAkuXUPElSah2AWCURKGALFDuHjvyJUL8vzZAt3R1B5qg/pub?gid=0&single=true&output=csv"
    format: "csv"
    headers: 2
    admin_single: "UKR"
    prefilter: "Number of People Reached != ''"
    date: "Date"
    date_type: "date"
    use_date: True
    input:
      - "Number of People Reached"
    output:
      - "PeopleReached"
    output_hxl:
      - "#reached+ind"
  allocations:
    source:
      "#value+cbpf+funding+total+usd": "CBPF"
      "default_source": "CERF"
    source_url:
      "#value+cbpf+funding+total+usd": "https://data.humdata.org/dataset/cbpf-allocations-and-contributions"
      "default_url": "https://data.humdata.org/dataset/cerf-allocations"
    dataset: "cerf-allocations"
    url: "https://cbpfgms.github.io/pfbi-data/download/full_pfmb_allocations.csv"
    format: "csv"
    sort:
      reverse: True
      keys:
        - "AllocationYear"
    date: "AllocationYear"
    date_type: "year"
    single_maxdate: True
    admin:
      - "CountryCode"
    filter_cols:
      - "FundType"
    subsets:
      - filter: "FundType == 'CBPF'"
        input:
          - "Budget"
        transform:
          Budget: "float(Budget)"
        sum:
          - formula: "Budget"
        output:
          - "CBPFFunding"
        output_hxl:
          - "#value+cbpf+funding+total+usd"
      - filter: "FundType == 'CERF'"
        input:
          - "Budget"
        transform:
          Budget: "float(Budget)"
        sum:
          - formula: "Budget"
        output:
          - "CERFFunding"
        output_hxl:
          - "#value+cerf+funding+total+usd"

fts:
  source: "OCHA"
  source_url:
    "#inneed+ind": "https://data.humdata.org/dataset/ukraine-key-figures-2022"
    "#value+funding+rrp+required+usd": "https://data.humdata.org/dataset/interagency-response-plans"
    "#value+funding+rrp+total+usd": "https://data.humdata.org/dataset/interagency-response-plans"
    "#value+funding+rrp+pct": "https://data.humdata.org/dataset/interagency-response-plans"
    "default_url": "https://data.humdata.org/dataset/fts-requirements-and-funding-data-for-ukraine"
  url: "https://api.hpc.tools/v"

unhcr:
  source: "UNHCR"
  source_url: "https://data.humdata.org/dataset/ukraine-refugee-situation"
  url: "https://data2.unhcr.org/population/get/sublocation?widget_id=283575&sv_id=54&population_group=5459,5460&forcesublocation=0&fromDate=1900-01-01"
  url_series: "https://data2.unhcr.org/population/get/timeseries?widget_id=283577&sv_id=54&population_group=5457&frequency=day&fromDate=1900-01-01"

scraper_subnational:
  population:
    source: "WorldPop/UNFPA"
    dataset: "gridded-population-estimates-for-ukraine-using-un-cod-ps-estimates-2020-version-1-0"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vS3_uBOV_uRDSxOggfBus_pkCs6Iw9lm0nAxzwG14YF_frpm13WPKiM1oNnQ9zrUA/pub?gid=1565793974&single=true&output=csv"
    format: "csv"
    admin:
      - "alpha_3"
      - "ADM1_PCODE"
    input:
      - "POPULATION"
    transform:
      "POPULATION": "get_numeric_if_possible(POPULATION)"
    output:
      - "Population"
    output_hxl:
      - "#population"
  health_facilities:
    source: "HOT"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vT-266S0iZDEvcQmxC2i7LNHWi4fUXtDkrwp8D6NMyHArxnegAYO9XXVnhuHaWvdxaoZTq7M6yGLaPX/pub?gid=1620744216&single=true&output=csv"
    format: "csv"
    admin:
      - "alpha_3"
      - "ADM1_PCODE"
    input:
      - "NUMPOINTS"
    output:
      - "NoHealthFacilities"
    output_hxl:
      - "#loc+count+health"
  whowhatwhere:
    dataset: "ukraine-who-does-what-where-3w"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vSMZQd0eSzgcdPnUfcdJvX4Y3gin8TjhEs-EmxoIAsl9ex5Zmxf09fZQKQJhTqFbG6WBazPRIx5qRop/pub?gid=594573511&single=true&output=csv"
    format: "csv"
    admin:
      - ~
      - "ADMIN1_ID"
    input:
      - "Number of Organisations"
      - "People Reached"
      - "Clusters Present"
    output:
      - "OrgCount"
      - "PeopleReached"
      - "ClustersPresent"
    output_hxl:
      - "#org+count+num"
      - "#reached+ind"
      - "#sector+cluster+names"

timeseries:
  casualties:
    source: "OHCHR"
    source_url: "https://data.humdata.org/dataset/ukraine-key-figures-2022"
    dataset: "ukraine-who-does-what-where-3w"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQIdedbZz0ehRC0b4fsWiP14R7MdtU1mpmwAkuXUPElSah2AWCURKGALFDuHjvyJUL8vzZAt3R1B5qg/pub?gid=0&single=true&output=csv"
    format: "csv"
    headers: 2
    date: "Date"
    date_type: "date"
    date_hxl: "#date"
    input:
      - "Civilian casualities(OHCHR) - Killed"
      - "Civilian casualities(OHCHR) - Injured"
    output:
      - "CiviliansKilled"
      - "CiviliansInjured"
    output_hxl:
      - "#affected+killed"
      - "#affected+injured"

copyfiles:
  - dataset: "ukraine-border-crossings"
    format: "geojson"
    filename: "UKR_Border_Crossings.geojson"
    hxltag: "#geojson"
  - dataset: "ukraine-hostilities"
    format: "geojson"
    filename: "UKR_Hostilities.geojson"
    hxltag: "#event+loc"

acled:
  source: "ACLED"
  source_url: "https://acleddata.com/ukraine-crisis/"
  url: "https://api.acleddata.com/acled/read.csv?iso=804&year=%d&limit=0"

idps:
  dataset: "ukraine-idp-estimates"
  format: "xlsx"
  sheet: "Current location of IDPs"
  headers: 2

countries:
  - UKR
  - POL
  - HUN
  - SVK
  - ROU
  - MDA
  - BLR
  - RUS

country_name_overrides:

country_name_mappings:

admin1_info:
  - {country: Ukraine, iso3: UKR, pcode: UA01, name: Avtonomna Respublika Krym}
  - {country: Ukraine, iso3: UKR, pcode: UA71, name: Cherkaska}
  - {country: Ukraine, iso3: UKR, pcode: UA74, name: Chernihivska}
  - {country: Ukraine, iso3: UKR, pcode: UA73, name: Chernivetska}
  - {country: Ukraine, iso3: UKR, pcode: UA12, name: Dnipropetrovska}
  - {country: Ukraine, iso3: UKR, pcode: UA14, name: Donetska}
  - {country: Ukraine, iso3: UKR, pcode: UA26, name: Ivano Frankivska}
  - {country: Ukraine, iso3: UKR, pcode: UA63, name: Kharkivska}
  - {country: Ukraine, iso3: UKR, pcode: UA65, name: Khersonska}
  - {country: Ukraine, iso3: UKR, pcode: UA68, name: Khmelnytska}
  - {country: Ukraine, iso3: UKR, pcode: UA35, name: Kirovohradska}
  - {country: Ukraine, iso3: UKR, pcode: UA80, name: Kyivska}
  - {country: Ukraine, iso3: UKR, pcode: UA32, name: Kyivska}
  - {country: Ukraine, iso3: UKR, pcode: UA44, name: Luhanska}
  - {country: Ukraine, iso3: UKR, pcode: UA46, name: Lvivska}
  - {country: Ukraine, iso3: UKR, pcode: UA48, name: Mykolaivska}
  - {country: Ukraine, iso3: UKR, pcode: UA51, name: Odeska}
  - {country: Ukraine, iso3: UKR, pcode: UA53, name: Poltavska}
  - {country: Ukraine, iso3: UKR, pcode: UA56, name: Rivnenska}
  - {country: Ukraine, iso3: UKR, pcode: UA85, name: Sevastopol}
  - {country: Ukraine, iso3: UKR, pcode: UA59, name: Sumska}
  - {country: Ukraine, iso3: UKR, pcode: UA61, name: Ternopilska}
  - {country: Ukraine, iso3: UKR, pcode: UA05, name: Vinnytska}
  - {country: Ukraine, iso3: UKR, pcode: UA07, name: Volynska}
  - {country: Ukraine, iso3: UKR, pcode: UA21, name: Zakarpatska}
  - {country: Ukraine, iso3: UKR, pcode: UA23, name: Zaporizka}
  - {country: Ukraine, iso3: UKR, pcode: UA18, name: Zhytomyrska}

admin1_name_mappings:
  "Chernigovskaja Oblast": "UA74"
  "Chernіvеtskaja Oblast": "UA73"
  "Crimea": "UA01"
  "Luganskaja Oblast": "UA44"
  "Rovenskaja Oblast": "UA56"
  "Sevastopol City": "UA85"
  "Zapоrіzskaja Oblast": "UA23"

admin1_name_replacements:
  " urban": ""
  "sud": "south"
  "ouest": "west"
  "est": "east"
  "nord": "north"
  "'": ""
  "/": " "
  ".": " "
  " region": ""
  " oblast": ""

admin1_fuzzy_dont:
  - "nord"
  - "north"
  - "sud"
  - "south"
  - "est"
  - "east"
  - "ouest"
  - "west"
