tabs:
  regional: "RegionalData"
  national: "NationalData"
  subnational: "SubnationalData"
  refugees_series: "RefugeesSeries"
  idps_macro: "IDPsMacro"
  fatalities: "Fatalities"
  sources: "Sources"


googlesheets:
  prod: "https://docs.google.com/spreadsheets/d/1a8OfzVRU5ZKDR9EoPu0TGSqb-HqedbmJC9v9jyYGDDE/edit#gid=0"
  test: "https://docs.google.com/spreadsheets/d/1wqnTR1i-DcFwh68BGGQgi4U9N4onLxqXvsmIhkchJVk/edit#gid=0"
  scratch: "https://docs.google.com/spreadsheets/d/1XfsqmwE9F0X551WfQU6KPqvlE0mW1auInxMSW_fj6Rc/edit#gid=0"

json:
  filepath: "all.json"

additional_sources:
  - indicator: "#date+start+conflict"
    source_date: "2022-02-24"
    source: "Meduza"
    source_url: "https://meduza.io/en/news/2022/02/24/putin-announces-start-of-military-operation-in-eastern-ukraine"
  - indicator: "#geojson"
    dataset: "ukraine-border-crossings"
    source: "Multiple Sources"

# national
scraper_national:
  population:
    source: "WorldPop/UNFPA"
    dataset: "gridded-population-estimates-for-ukraine-using-un-cod-ps-estimates-2020-version-1-0"
    url: "http://api.worldbank.org/v2/en/indicator/SP.POP.TOTL?downloadformat=excel&dataformat=list"
    format: "xls"
    sheet: "Data"
    headers: 3
    prefilter: "Value != ''"
    admin:
      - "Country Code"
    date: "Year"
    date_type: "year"
    input:
      - "Value"
    output:
      - "Population"
    output_hxl:
      - "#population"
  casualties:
    source: "OHCHR"
    source_url: "https://data.humdata.org/dataset/ukraine-key-figures-2022"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQIdedbZz0ehRC0b4fsWiP14R7MdtU1mpmwAkuXUPElSah2AWCURKGALFDuHjvyJUL8vzZAt3R1B5qg/pub?gid=0&single=true&output=csv"
    format: "csv"
    headers: 2
    admin_single: "UKR"
    date: "Date"
    date_type: "date"
    input:
      - "Civilian casualities(OHCHR) - Killed"
      - "Civilian casualities(OHCHR) - Injured"
    output:
      - "CiviliansKilled"
      - "CiviliansInjured"
    output_hxl:
      - "#affected+killed"
      - "#affected+injured"
  attacks_education:
    source: "Multiple Sources"
    source_url: "https://data.humdata.org/dataset/ukraine-key-figures-2022"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQIdedbZz0ehRC0b4fsWiP14R7MdtU1mpmwAkuXUPElSah2AWCURKGALFDuHjvyJUL8vzZAt3R1B5qg/pub?gid=0&single=true&output=csv"
    format: "csv"
    headers: 2
    admin_single: "UKR"
    prefilter: "Attacks on Education Facilities != ''"
    date: "Date"
    date_type: "date"
    use_date: True
    input:
      - "Attacks on Education Facilities"
    output:
      - "AttacksOnEducation"
    output_hxl:
      - "#indicator+attacks+education+num"
  attacks_healthcare:
    source: "WHO"
    source_url: "https://data.humdata.org/dataset/ukraine-who-ssa"
    url: "https://proxy.hxlstandard.org/data.csv?tagger-match-all=on&tagger-02-header=reportid&tagger-02-tag=%23meta%2Bid&tagger-03-header=lastmodified&tagger-03-tag=%23date%2Breported&tagger-07-header=country&tagger-07-tag=%23country%2Bname&tagger-08-header=countryiso2code&tagger-08-tag=%23country%2Bcode%2Bv_iso2&tagger-09-header=countryiso3code&tagger-09-tag=%23country%2Bcode&tagger-10-header=attacktimestamp&tagger-10-tag=%23date%2Boccurred&tagger-11-header=classificationid&tagger-11-tag=%23status%2Bcode&tagger-12-header=classification&tagger-12-tag=%23status%2Bname&tagger-13-header=attacktype&tagger-13-tag=%23event%2Btype&tagger-14-header=attacktypeid&tagger-14-tag=%23event%2Bcode&tagger-15-header=victimstotalinjured&tagger-15-tag=%23affected%2Binjured&tagger-16-header=victimstotaldeath&tagger-16-tag=%23affected%2Bkilled&tagger-17-header=hcfacilities&tagger-17-tag=%23event%2Bhcfacilities%2Baffected&tagger-18-header=hctransport&tagger-18-tag=%23event%2Bhctransport%2Baffected&tagger-19-header=hcpersonnel&tagger-19-tag=%23event%2Bhcpersonnel%2Baffected&tagger-20-header=hcsuppliesassets&tagger-20-tag=%23event%2Bhcsuppliesassets%2Baffected&tagger-21-header=hcwarehousestorage&tagger-21-tag=%23event%2Bhcwarehouse%2Baffected&tagger-22-header=hcpatients&tagger-22-tag=%23event%2Bhcpatients%2Baffected&tagger-23-header=hcother&tagger-23-tag=%23event%2Bhcother%2Baffected&tagger-24-header=typeoffacility&tagger-24-tag=%23event%2Bfacility%2Btype&tagger-25-header=facilityother&tagger-25-tag=%23event%2Bfacility%2Bother%2Btype&tagger-26-header=hwabducton&tagger-26-tag=%23affected%2Bhw%2Babducted&tagger-27-header=hwarrest&tagger-27-tag=%23affected%2Bhw%2Barrested&tagger-28-header=hwdetention&tagger-28-tag=%23affected%2Bhw%2Bdetained&tagger-29-header=patientabduction&tagger-29-tag=%23affected%2Bpatient%2Babducted&tagger-30-header=patientarrest&tagger-30-tag=%23affected%2Bpatient%2Barrested&tagger-31-header=patientdetention&tagger-31-tag=%23affected%2Bpatient%2Bdetained&url=https%3A%2F%2Fextranet.who.int%2Fssa%2FRef%2FGetDashboardFullReport%3FCountries%3D229%26Types%3D0%26DaterangeSTART%3D2022-02-24&header-row=1&dest=data_view"
    format: "csv"
    use_hxl: True
    admin_single: "UKR"
    input:
      - "#meta+id"
    transform:
      "#meta+id": "1"
    sum:
      - formula: "#meta+id"
    output:
      - "AttacksOnHealthcare"
    output_hxl:
      - "#indicator+attacks+healthcare+num"
  allocations:
    source:
      "#value+cbpf+funding+total+usd": "CBPF"
      "default_source": "CERF"
    source_url:
      "#value+cbpf+funding+total+usd": "https://data.humdata.org/dataset/cbpf-allocations-and-contributions"
      "default_url": "https://data.humdata.org/dataset/cerf-allocations"
    dataset: "cerf-allocations"
    url: "https://cbpfgms.github.io/pfbi-data/download/full_pfmb_allocations.csv"
    format: "csv"
    sort:
      reverse: True
      keys:
        - "AllocationYear"
    date: "AllocationYear"
    date_type: "year"
    single_maxdate: True
    admin:
      - "CountryCode"
    filter_cols:
      - "FundType"
    subsets:
      - filter: "FundType == 'CBPF'"
        input:
          - "Budget"
        transform:
          Budget: "float(Budget)"
        sum:
          - formula: "Budget"
        output:
          - "CBPFFunding"
        output_hxl:
          - "#value+cbpf+funding+total+usd"
      - filter: "FundType == 'CERF'"
        input:
          - "Budget"
        transform:
          Budget: "float(Budget)"
        sum:
          - formula: "Budget"
        output:
          - "CERFFunding"
        output_hxl:
          - "#value+cerf+funding+total+usd"

fts:
  source: "OCHA"
  source_url:
    "#inneed+ind": "https://data.humdata.org/dataset/ukraine-key-figures-2022"
    "#value+funding+rrp+required+usd": "https://data.humdata.org/dataset/interagency-response-plans"
    "#value+funding+rrp+total+usd": "https://data.humdata.org/dataset/interagency-response-plans"
    "#value+funding+rrp+pct": "https://data.humdata.org/dataset/interagency-response-plans"
    "default_url": "https://data.humdata.org/dataset/fts-requirements-and-funding-data-for-ukraine"
  url: "https://api.hpc.tools/v"

unhcr:
  source: "UNHCR"
  source_url: "https://data.humdata.org/dataset/ukraine-refugee-situation"
  url: "https://data2.unhcr.org/population/get/sublocation?widget_id=283575&sv_id=54&population_group=5459,5460&forcesublocation=0&fromDate=1900-01-01"
  url_series: "https://data2.unhcr.org/population/get/timeseries?widget_id=283577&sv_id=54&population_group=5457&frequency=day&fromDate=1900-01-01"

scraper_subnational:
  population:
    source: "WorldPop/UNFPA"
    dataset: "gridded-population-estimates-for-ukraine-using-un-cod-ps-estimates-2020-version-1-0"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vS3_uBOV_uRDSxOggfBus_pkCs6Iw9lm0nAxzwG14YF_frpm13WPKiM1oNnQ9zrUA/pub?gid=1565793974&single=true&output=csv"
    format: "csv"
    admin:
      - "alpha_3"
      - "ADM1_PCODE"
    input:
      - "POPULATION"
    transform:
      "POPULATION": "get_numeric_if_possible(POPULATION)"
    output:
      - "Population"
    output_hxl:
      - "#population"
  health_facilities:
    source: "HOT"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vT-266S0iZDEvcQmxC2i7LNHWi4fUXtDkrwp8D6NMyHArxnegAYO9XXVnhuHaWvdxaoZTq7M6yGLaPX/pub?gid=1620744216&single=true&output=csv"
    format: "csv"
    admin:
      - "alpha_3"
      - "ADM1_PCODE"
    input:
      - "NUMPOINTS"
    output:
      - "NoHealthFacilities"
    output_hxl:
      - "#loc+count+health"
  whowhatwhere:
    source: "Multiple Sources"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vSwZuAI7rAsW1s0yIPPClIYbEMvnAC01P_bsMbR6RtDl4-fR3T0B6qVOW4Xq29W47i20iGeFFft5Ntk/pub?gid=0&single=true&output=csv"
    format: "csv"
    admin:
      - ~
      - "admin1Pcode"
    input:
      - "orgCountRound3"
    output:
      - "OrgCountAdm1"
    output_hxl:
      - "#org+count+num"

acled:
  source: "ACLED"
  source_url: "https://acleddata.com/ukraine-crisis/"
  url: "https://api.acleddata.com/acled/read.csv?iso=804&year=%d&limit=0"

geojson:
  dataset: "ukraine-border-crossings"

idps:
  dataset: "ukraine-idp-estimates"
  format: "xlsx"
  sheet: "Current location of IDPs"
  headers: 2

countries:
  - UKR
  - POL
  - HUN
  - SVK
  - ROU
  - MDA
  - BLR
  - RUS

country_name_overrides:

country_name_mappings:

admin1_info:
  - {country: Ukraine, iso3: UKR, pcode: UA01, name: Avtonomna Respublika Krym}
  - {country: Ukraine, iso3: UKR, pcode: UA71, name: Cherkaska}
  - {country: Ukraine, iso3: UKR, pcode: UA74, name: Chernihivska}
  - {country: Ukraine, iso3: UKR, pcode: UA73, name: Chernivetska}
  - {country: Ukraine, iso3: UKR, pcode: UA12, name: Dnipropetrovska}
  - {country: Ukraine, iso3: UKR, pcode: UA14, name: Donetska}
  - {country: Ukraine, iso3: UKR, pcode: UA26, name: Ivano Frankivska}
  - {country: Ukraine, iso3: UKR, pcode: UA63, name: Kharkivska}
  - {country: Ukraine, iso3: UKR, pcode: UA65, name: Khersonska}
  - {country: Ukraine, iso3: UKR, pcode: UA68, name: Khmelnytska}
  - {country: Ukraine, iso3: UKR, pcode: UA35, name: Kirovohradska}
  - {country: Ukraine, iso3: UKR, pcode: UA80, name: Kyivska}
  - {country: Ukraine, iso3: UKR, pcode: UA32, name: Kyivska}
  - {country: Ukraine, iso3: UKR, pcode: UA44, name: Luhanska}
  - {country: Ukraine, iso3: UKR, pcode: UA46, name: Lvivska}
  - {country: Ukraine, iso3: UKR, pcode: UA48, name: Mykolaivska}
  - {country: Ukraine, iso3: UKR, pcode: UA51, name: Odeska}
  - {country: Ukraine, iso3: UKR, pcode: UA53, name: Poltavska}
  - {country: Ukraine, iso3: UKR, pcode: UA56, name: Rivnenska}
  - {country: Ukraine, iso3: UKR, pcode: UA85, name: Sevastopol}
  - {country: Ukraine, iso3: UKR, pcode: UA59, name: Sumska}
  - {country: Ukraine, iso3: UKR, pcode: UA61, name: Ternopilska}
  - {country: Ukraine, iso3: UKR, pcode: UA05, name: Vinnytska}
  - {country: Ukraine, iso3: UKR, pcode: UA07, name: Volynska}
  - {country: Ukraine, iso3: UKR, pcode: UA21, name: Zakarpatska}
  - {country: Ukraine, iso3: UKR, pcode: UA23, name: Zaporizka}
  - {country: Ukraine, iso3: UKR, pcode: UA18, name: Zhytomyrska}

admin1_name_mappings:
  "Chernigovskaja Oblast": "UA74"
  "Chernіvеtskaja Oblast": "UA73"
  "Crimea": "UA01"
  "Luganskaja Oblast": "UA44"
  "Rovenskaja Oblast": "UA56"
  "Sevastopol City": "UA85"
  "Zapоrіzskaja Oblast": "UA23"

admin1_name_replacements:
  " urban": ""
  "sud": "south"
  "ouest": "west"
  "est": "east"
  "nord": "north"
  "'": ""
  "/": " "
  ".": " "
  " region": ""
  " oblast": ""

admin1_fuzzy_dont:
  - "nord"
  - "north"
  - "sud"
  - "south"
  - "est"
  - "east"
  - "ouest"
  - "west"
