tabs:
  regional: "RegionalData"
  national: "NationalData"
  subnational: "SubnationalData"
  refugees_series: "RefugeesSeries"
  fatalities: "Fatalities"
  sources: "Sources"


googlesheets:
  prod: "https://docs.google.com/spreadsheets/d/1a8OfzVRU5ZKDR9EoPu0TGSqb-HqedbmJC9v9jyYGDDE/edit#gid=0"
  test: "https://docs.google.com/spreadsheets/d/1wqnTR1i-DcFwh68BGGQgi4U9N4onLxqXvsmIhkchJVk/edit#gid=0"
  scratch: "https://docs.google.com/spreadsheets/d/1XfsqmwE9F0X551WfQU6KPqvlE0mW1auInxMSW_fj6Rc/edit#gid=0"

json:
  filepath: "all.json"

additional_sources:
  - indicator: "#geojson"
    dataset: "ukraine-border-crossings"

# national
scraper_national:
  population:
    source: "WorldPop"
    dataset: "worldpop-population-counts-for-ukraine"
    url: "http://api.worldbank.org/v2/en/indicator/SP.POP.TOTL?downloadformat=excel&dataformat=list"
    format: "xls"
    sheet: "Data"
    headers: 3
    prefilter: "Value != ''"
    adm_cols:
      - "Country Code"
    date_col: "Year"
    date_type: "year"
    input_cols:
      - "Value"
    output_cols:
      - "Population"
    output_hxltags:
      - "#population"
  casualties:
    source: "OHCHR"
    source_url: "https://data.humdata.org/dataset/ukraine-key-figures-2022"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQIdedbZz0ehRC0b4fsWiP14R7MdtU1mpmwAkuXUPElSah2AWCURKGALFDuHjvyJUL8vzZAt3R1B5qg/pub?gid=0&single=true&output=csv"
    format: "csv"
    headers: 2
    adm_single: "UKR"
    date_col: "Date"
    date_type: "date"
    input_cols:
      - "Civilian casualities(OHCHR) - Killed"
      - "Civilian casualities(OHCHR) - Injured"
    output_cols:
      - "CiviliansKilled"
      - "CiviliansInjured"
    output_hxltags:
      - "#affected+killed"
      - "#affected+injured"
  allocations:
    source:
      "#value+cbpf+funding+total+usd": "CBPF"
      "default_source": "CERF"
    source_url:
      "#value+cbpf+funding+total+usd": "https://data.humdata.org/dataset/cbpf-allocations-and-contributions"
      "default_url": "https://data.humdata.org/dataset/cerf-allocations"
    dataset: "cerf-allocations"
    url: "https://cbpfgms.github.io/pfbi-data/download/full_pfmb_allocations.csv"
    format: "csv"
    sort:
      reverse: True
      keys:
        - "AllocationYear"
    date_col: "AllocationYear"
    date_type: "year"
    single_maxdate: True
    adm_cols:
      - "CountryCode"
    filter_cols:
      - "FundType"
    subsets:
      - filter: "FundType == 'CBPF'"
        input_cols:
          - "Budget"
        input_transforms:
          Budget: "float(Budget)"
        sum_cols:
          - formula: "Budget"
            mustbepopulated: False
        output_cols:
          - "CBPFFunding"
        output_hxltags:
          - "#value+cbpf+funding+total+usd"
      - filter: "FundType == 'CERF'"
        input_cols:
          - "Budget"
        input_transforms:
          Budget: "float(Budget)"
        sum_cols:
          - formula: "Budget"
            mustbepopulated: False
        output_cols:
          - "CERFFunding"
        output_hxltags:
          - "#value+cerf+funding+total+usd"

fts:
  source: "OCHA"
  source_url:
    "#inneed+ind": "https://data.humdata.org/dataset/ukraine-key-figures-2022"
    "#value+funding+rrp+required+usd": "https://docs.google.com/spreadsheets/d/e/2PACX-1vRzvb2ZKLS95aToa_SBYfsZIFhcL_0rvfir5kSUNzl7KNY8UIAVH9AyBZ2I-d5yAZly4l6S15bCVM_d/pub?gid=918365211&single=true&output=csv"
    "#value+funding+rrp+total+usd": "https://docs.google.com/spreadsheets/d/e/2PACX-1vRzvb2ZKLS95aToa_SBYfsZIFhcL_0rvfir5kSUNzl7KNY8UIAVH9AyBZ2I-d5yAZly4l6S15bCVM_d/pub?gid=918365211&single=true&output=csv"
    "#value+funding+rrp+pct": "https://docs.google.com/spreadsheets/d/e/2PACX-1vRzvb2ZKLS95aToa_SBYfsZIFhcL_0rvfir5kSUNzl7KNY8UIAVH9AyBZ2I-d5yAZly4l6S15bCVM_d/pub?gid=918365211&single=true&output=csv"
    "default_url": "https://data.humdata.org/dataset/fts-requirements-and-funding-data-for-ukraine"
  url: "https://api.hpc.tools/v"

unhcr:
  source: "UNHCR"
  source_url: "https://data2.unhcr.org/en/situations/ukraine"
  url: "https://data2.unhcr.org/population/get/sublocation?widget_id=283575&sv_id=54&population_group=5459,5460&forcesublocation=0&fromDate=1900-01-01"
  url_series: "https://data2.unhcr.org/population/get/timeseries?widget_id=283577&sv_id=54&population_group=5457&frequency=day&fromDate=1900-01-01"

scraper_subnational:
  population:
    source: "WorldPop"
    dataset: "worldpop-population-counts-for-ukraine"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vS3_uBOV_uRDSxOggfBus_pkCs6Iw9lm0nAxzwG14YF_frpm13WPKiM1oNnQ9zrUA/pub?gid=1565793974&single=true&output=csv"
    format: "csv"
    adm_cols:
      - "alpha_3"
      - "ADM1_PCODE"
    input_cols:
      - "POPULATION"
    input_transforms:
      "POPULATION": "get_numeric_if_possible(POPULATION)"
    output_cols:
      - "Population"
    output_hxltags:
      - "#population"
  health_facilities:
    source: "HOT"
    url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vT-266S0iZDEvcQmxC2i7LNHWi4fUXtDkrwp8D6NMyHArxnegAYO9XXVnhuHaWvdxaoZTq7M6yGLaPX/pub?gid=1620744216&single=true&output=csv"
    format: "csv"
    adm_cols:
      - "alpha_3"
      - "ADM1_PCODE"
    input_cols:
      - "NUMPOINTS"
    output_cols:
      - "NoHealthFacilities"
    output_hxltags:
      - "#loc+count+health"

acled:
  source: "ACLED"
  source_url: "https://acleddata.com/ukraine-crisis/#dash"
  url: "https://api.acleddata.com/acled/read.csv?iso=804&year=%d&limit=0"
  start_date: "2022-02-04"

geojson:
  dataset: "ukraine-border-crossings"

countries:
  - UKR
  - POL
  - HUN
  - SVK
  - ROU
  - MDA
  - BLR
  - RUS

country_name_overrides:

country_name_mappings:

admin1_info:
  - {country: Ukraine, iso3: UKR, pcode: UA01, name: Avtonomna Respublika Krym}
  - {country: Ukraine, iso3: UKR, pcode: UA71, name: Cherkaska}
  - {country: Ukraine, iso3: UKR, pcode: UA74, name: Chernihivska}
  - {country: Ukraine, iso3: UKR, pcode: UA73, name: Chernivetska}
  - {country: Ukraine, iso3: UKR, pcode: UA12, name: Dnipropetrovska}
  - {country: Ukraine, iso3: UKR, pcode: UA14, name: Donetska}
  - {country: Ukraine, iso3: UKR, pcode: UA26, name: Ivano Frankivska}
  - {country: Ukraine, iso3: UKR, pcode: UA63, name: Kharkivska}
  - {country: Ukraine, iso3: UKR, pcode: UA65, name: Khersonska}
  - {country: Ukraine, iso3: UKR, pcode: UA68, name: Khmelnytska}
  - {country: Ukraine, iso3: UKR, pcode: UA35, name: Kirovohradska}
  - {country: Ukraine, iso3: UKR, pcode: UA80, name: Kyivska}
  - {country: Ukraine, iso3: UKR, pcode: UA32, name: Kyivska}
  - {country: Ukraine, iso3: UKR, pcode: UA44, name: Luhanska}
  - {country: Ukraine, iso3: UKR, pcode: UA46, name: Lvivska}
  - {country: Ukraine, iso3: UKR, pcode: UA48, name: Mykolaivska}
  - {country: Ukraine, iso3: UKR, pcode: UA51, name: Odeska}
  - {country: Ukraine, iso3: UKR, pcode: UA53, name: Poltavska}
  - {country: Ukraine, iso3: UKR, pcode: UA56, name: Rivnenska}
  - {country: Ukraine, iso3: UKR, pcode: UA85, name: Sevastopol}
  - {country: Ukraine, iso3: UKR, pcode: UA59, name: Sumska}
  - {country: Ukraine, iso3: UKR, pcode: UA61, name: Ternopilska}
  - {country: Ukraine, iso3: UKR, pcode: UA05, name: Vinnytska}
  - {country: Ukraine, iso3: UKR, pcode: UA07, name: Volynska}
  - {country: Ukraine, iso3: UKR, pcode: UA21, name: Zakarpatska}
  - {country: Ukraine, iso3: UKR, pcode: UA23, name: Zaporizka}
  - {country: Ukraine, iso3: UKR, pcode: UA18, name: Zhytomyrska}

admin1_name_mappings:
  "Chernigovskaja Oblast": "UA74"
  "Chernіvеtskaja Oblast": "UA73"
  "Crimea": "UA01"
  "Luganskaja Oblast": "UA44"
  "Rovenskaja Oblast": "UA56"
  "Sevastopol City": "UA85"
  "Zapоrіzskaja Oblast": "UA23"

admin1_name_replacements:
  " urban": ""
  "sud": "south"
  "ouest": "west"
  "est": "east"
  "nord": "north"
  "'": ""
  "/": " "
  ".": " "
  " region": ""
  " oblast": ""

admin1_fuzzy_dont:
  - "nord"
  - "north"
  - "sud"
  - "south"
  - "est"
  - "east"
  - "ouest"
  - "west"
